// Curated suggestions; members may also enter a school not listed here.
export const UNIVERSITIES = [
  'American University','Arizona State University','Babson College','Barnard College','Baruch College','Binghamton University','Boston College','Boston University','Brandeis University','Brooklyn College','Brown University','Carnegie Mellon University','City College of New York','Columbia University','Cornell University','Dartmouth College','Drexel University','Duke University','Emory University','Florida Atlantic University','Florida International University','Florida State University','Fordham University','George Washington University','Georgetown University','Georgia Institute of Technology','Harvard University','Hofstra University','Hunter College','Indiana University Bloomington','Johns Hopkins University','Lehigh University','Massachusetts Institute of Technology','McGill University','Michigan State University','New York University','Northeastern University','Northwestern University','Ohio State University','Penn State University','Princeton University','Purdue University','Queens College','Rice University','Rutgers University','San Diego State University','Stanford University','Stony Brook University','Syracuse University','Technion – Israel Institute of Technology','Tel Aviv University','Temple University','The Hebrew University of Jerusalem','Touro University','Tufts University','Tulane University','University at Albany','University at Buffalo','University of Arizona','University of California, Berkeley','University of California, Davis','University of California, Irvine','University of California, Los Angeles (UCLA)','University of California, San Diego','University of California, Santa Barbara','University of Central Florida','University of Chicago','University of Colorado Boulder','University of Connecticut','University of Delaware','University of Florida','University of Georgia','University of Illinois Urbana-Champaign','University of Maryland','University of Massachusetts Amherst','University of Miami','University of Michigan','University of Minnesota','University of North Carolina at Chapel Hill','University of Pennsylvania','University of Pittsburgh','University of Rochester','University of South Florida','University of Southern California','University of Texas at Austin','University of Toronto','University of Vermont','University of Virginia','University of Washington','University of Wisconsin–Madison','Vanderbilt University','Washington University in St. Louis','Yale University','Yeshiva University'
];
export function searchUniversities(query: string) {
  const terms = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  if (!terms.length) return [];
  return UNIVERSITIES.filter(name => terms.every(term => name.toLowerCase().includes(term))).slice(0,6);
}
